name: Build APK for arm64 and arm32

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'
          channel: 'stable'

      - name: Create Keystore & Properties
        run: |
          mkdir -p android/app
          keytool -genkey -v -keystore android/app/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass 12345678 -keypass 12345678 -dname "CN=VidMate, OU=App, O=MyCompany, L=City, S=State, C=US"
          echo "storePassword=12345678" > android/key.properties
          echo "keyPassword=12345678" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Update pubspec with flutter_inappwebview
        run: |
          cat << 'EOF' > pubspec.yaml
          name: ytdownloader
          description: "A new Flutter project."
          publish_to: 'none'
          version: 1.0.0+1
          environment:
            sdk: ^3.12.2
          dependencies:
            flutter:
              sdk: flutter
            cupertino_icons: ^1.0.8
            flutter_inappwebview: ^6.1.5
            permission_handler: ^11.4.0
          dev_dependencies:
            flutter_test:
              sdk: flutter
            flutter_lints: ^6.0.0
          flutter:
            uses-material-design: true
          EOF

      - name: Get dependencies
        run: flutter pub get

      - name: Fix WebView Proguard Issue Automatically
        run: |
          GRADLE_FILE="$HOME/.pub-cache/hosted/pub.dev/flutter_inappwebview_android-1.1.3/android/build.gradle"
          if [ -f "$GRADLE_FILE" ]; then
            sed -i "s/proguard-android.txt/proguard-android-optimize.txt/g" "$GRADLE_FILE"
            echo "Successfully patched flutter_inappwebview_android build.gradle"
          fi

      - name: Build APK release
        run: flutter build apk --release --target-platform android-arm,android-arm64

      - name: Upload APK directly
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
