name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # flutter-version ကို ဖြုတ်လိုက်ပြီး stable လို့ပဲ ထားခြင်းဖြင့် အမြဲတမ်း နောက်ဆုံးပေါ် Version ကို သုံးပေးပါမည်။
          channel: 'stable' 

      - name: Generate Keystore & key.properties
        run: |
          mkdir -p android/app
          keytool -genkey -v -keystore android/app/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass 12345678 -keypass 12345678 -dname "CN=VidMate Clone, OU=App, O=MyCompany, L=City, S=State, C=US"
          
          echo "storePassword=12345678" > android/key.properties
          echo "keyPassword=12345678" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VidMate-Clone-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
