name: Build Specific ABIs APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'
          channel: 'stable'

      - name: Create Keystore & Properties
        run: |
          mkdir -p android/app
          keytool -genkey -v -keystore android/app/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass 12345678 -keypass 12345678 -dname "CN=VidMate, OU=App, O=MyCompany, L=City, S=State, C=US"
          echo "storePassword=12345678" > android/key.properties
          echo "keyPassword=12345678" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK for arm64-v8a and armeabi-v7a
        run: flutter build apk --release --no-shrink --target-platform android-arm,android-arm64
